# Generated by Django 5.2.17 on 2026-09-03 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('collecting_feedback', 'Collecting feedback'), ('retrospective', 'Retrospective'), ('completed', 'Completed')], default='collecting_feedback', max_length=32)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_cycles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cycles', to='projects.project')),
            ],
            options={
                'ordering': ['-opens_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['collecting_feedback', 'retrospective', 'completed'])), name='feedback_cycle_status_is_mvp_status'), models.CheckConstraint(condition=models.Q(('closes_at__isnull', True), ('closes_at__gte', models.F('opens_at')), _connector='OR'), name='feedback_cycle_closes_at_not_before_opens_at'), models.UniqueConstraint(condition=models.Q(('status', 'completed'), _negated=True), fields=('project',), name='unique_active_feedback_cycle_per_project')],
            },
        ),
    ]
