# Generated by Django 5.2.17 on 2026-09-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_feedbackcycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('continue', 'Continue')], max_length=16)),
                ('text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cards', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cards', to='projects.feedbackcycle')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['start', 'stop', 'continue'])), name='feedback_card_category_is_mvp_category')],
            },
        ),
    ]
