# Generated by Django 5.2.17 on 2026-09-04 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_feedbackcluster_feedbackcard_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackClusterVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cycle', 'voter', 'cluster'],
            },
        ),
        migrations.AddField(
            model_name='feedbackcycle',
            name='voting_status',
            field=models.CharField(choices=[('clustering', 'Clustering'), ('open', 'Voting open'), ('closed', 'Voting closed')], default='clustering', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='feedbackcycle',
            constraint=models.CheckConstraint(condition=models.Q(('voting_status__in', ['clustering', 'open', 'closed'])), name='feedback_cycle_voting_status_is_mvp_status'),
        ),
        migrations.AddField(
            model_name='feedbackclustervote',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.feedbackcluster'),
        ),
        migrations.AddField(
            model_name='feedbackclustervote',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_votes', to='projects.feedbackcycle'),
        ),
        migrations.AddField(
            model_name='feedbackclustervote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cluster_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feedbackclustervote',
            constraint=models.UniqueConstraint(fields=('cycle', 'voter', 'cluster'), name='unique_feedback_cluster_vote_allocation'),
        ),
        migrations.AddConstraint(
            model_name='feedbackclustervote',
            constraint=models.CheckConstraint(condition=models.Q(('vote_count__gte', 0), ('vote_count__lte', 3)), name='feedback_cluster_vote_count_is_three_vote_budget'),
        ),
    ]
