# Generated by Django 5.2.17 on 2026-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_feedbackclustervote_feedbackcycle_voting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcluster',
            name='discussion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedbackcluster',
            name='discussion_status',
            field=models.CharField(choices=[('pending', 'Not started'), ('discussed', 'Discussed'), ('skipped', 'Skipped'), ('deferred', 'Deferred')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='feedbackcluster',
            constraint=models.CheckConstraint(condition=models.Q(('discussion_status__in', ['pending', 'discussed', 'skipped', 'deferred'])), name='feedback_cluster_discussion_status_is_mvp_status'),
        ),
    ]
