# Generated by Django 5.2.17 on 2026-09-04 15:59

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_retrospectivedecision_actionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('audio_upload', 'Audio upload'), ('video_upload', 'Video upload'), ('transcript_file', 'Transcript file'), ('pasted_transcript', 'Pasted transcript')], max_length=32)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('source_file', models.FileField(blank=True, upload_to=projects.models.meeting_material_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pasted_transcript_text', models.TextField(blank=True, default='')),
                ('text_character_count', models.PositiveIntegerField(default=0)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_materials', to='projects.feedbackcycle')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_meeting_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_type__in', ['audio_upload', 'video_upload', 'transcript_file', 'pasted_transcript'])), name='meeting_material_source_type_is_mvp_type'), models.CheckConstraint(condition=models.Q(('processing_status__in', ['queued', 'processing', 'succeeded', 'failed'])), name='meeting_material_status_is_mvp_status')],
            },
        ),
    ]
