# Generated by Django 5.2.17 on 2026-09-04 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_meetingmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMaterialExtractionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrospective_summary_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_draft', to='projects.meetingmaterial')),
            ],
            options={
                'ordering': ['meeting_material_id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMaterialDraftDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic_candidate', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_material_draft_decisions', to='projects.feedbackcluster')),
                ('extraction_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_decisions', to='projects.meetingmaterialextractiondraft')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMaterialDraftActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('owner_candidate', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('topic_candidate', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_material_draft_action_items', to=settings.AUTH_USER_MODEL)),
                ('matched_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_material_draft_action_items', to='projects.feedbackcluster')),
                ('extraction_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_action_items', to='projects.meetingmaterialextractiondraft')),
            ],
            options={
                'ordering': ['due_date', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMaterialTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_transcript', to='projects.meetingmaterial')),
            ],
            options={
                'ordering': ['meeting_material_id'],
            },
        ),
    ]
