# Generated by Django 5.2.17 on 2026-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_meetingmaterialextractiondraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcycle',
            name='approved_retrospective_summary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingmaterialextractiondraft',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('discarded', 'Discarded')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='meetingmaterialextractiondraft',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'discarded'])), name='meeting_material_draft_review_status_is_mvp_status'),
        ),
    ]
