# Generated by Django 5.2.17 on 2026-09-05 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_feedbackcycle_approved_retrospective_summary_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcycle',
            name='summary_active_member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RetrospectiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='projects.feedbackcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'user'), name='unique_retrospective_attendance')],
            },
        ),
    ]
