"""URL configuration for the weekly_planner project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from weekly_planner.views import (
    ActionItemCreateView,
    ActionItemOwnerCompleteView,
    ActionItemUpdateView,
    FeedbackCardCreateView,
    FeedbackCardDeleteView,
    FeedbackCardClusterMoveView,
    FeedbackCardUpdateView,
    FeedbackClusterCreateView,
    FeedbackClusterDiscussionUpdateView,
    FeedbackClusterMergeView,
    FeedbackClusterRenameView,
    FeedbackClusterSplitView,
    FeedbackClusterSuggestionAcceptView,
    FeedbackClusterSuggestionEditView,
    FeedbackClusterSuggestionGenerateView,
    FeedbackClusterSuggestionIgnoreView,
    FeedbackCycleCreateView,
    FeedbackCycleRevealView,
    FeedbackCycleVoteSubmitView,
    FeedbackCycleVotingCloseView,
    FeedbackCycleVotingOpenView,
    FeedbackSubmissionView,
    HomeView,
    MeetingMaterialCreateView,
    MeetingMaterialExtractionDraftApproveView,
    MeetingMaterialExtractionDraftDiscardView,
    MeetingMaterialRetryView,
    ProjectDashboardView,
    ProjectsView,
    RetrospectiveBoardView,
    RetrospectiveDecisionCreateView,
    RetrospectiveDecisionUpdateView,
    SignUpView,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/signup/", SignUpView.as_view(), name="signup"),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path(
        "projects/<int:project_id>/",
        ProjectDashboardView.as_view(),
        name="project_dashboard",
    ),
    path(
        "projects/<int:project_id>/cycles/new/",
        FeedbackCycleCreateView.as_view(),
        name="feedback_cycle_create",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/feedback/",
        FeedbackSubmissionView.as_view(),
        name="feedback_submission",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/feedback/<str:category>/add/",
        FeedbackCardCreateView.as_view(),
        name="feedback_card_create",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/feedback/<int:card_id>/edit/",
        FeedbackCardUpdateView.as_view(),
        name="feedback_card_update",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/feedback/<int:card_id>/delete/",
        FeedbackCardDeleteView.as_view(),
        name="feedback_card_delete",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/reveal/",
        FeedbackCycleRevealView.as_view(),
        name="feedback_cycle_reveal",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/",
        RetrospectiveBoardView.as_view(),
        name="retrospective_board",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/clusters/add/",
        FeedbackClusterCreateView.as_view(),
        name="feedback_cluster_create",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/clusters/<int:cluster_id>/rename/",
        FeedbackClusterRenameView.as_view(),
        name="feedback_cluster_rename",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/cards/<int:card_id>/move/",
        FeedbackCardClusterMoveView.as_view(),
        name="feedback_card_move",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/clusters/<int:cluster_id>/merge/",
        FeedbackClusterMergeView.as_view(),
        name="feedback_cluster_merge",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/clusters/<int:cluster_id>/split/",
        FeedbackClusterSplitView.as_view(),
        name="feedback_cluster_split",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/suggestions/generate/",
        FeedbackClusterSuggestionGenerateView.as_view(),
        name="feedback_cluster_suggestions_generate",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/suggestions/edit/",
        FeedbackClusterSuggestionEditView.as_view(),
        name="feedback_cluster_suggestions_edit",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/suggestions/accept/",
        FeedbackClusterSuggestionAcceptView.as_view(),
        name="feedback_cluster_suggestions_accept",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/suggestions/ignore/",
        FeedbackClusterSuggestionIgnoreView.as_view(),
        name="feedback_cluster_suggestions_ignore",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/voting/open/",
        FeedbackCycleVotingOpenView.as_view(),
        name="feedback_cycle_voting_open",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/voting/submit/",
        FeedbackCycleVoteSubmitView.as_view(),
        name="feedback_cycle_vote_submit",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/voting/close/",
        FeedbackCycleVotingCloseView.as_view(),
        name="feedback_cycle_voting_close",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/meeting-materials/add/",
        MeetingMaterialCreateView.as_view(),
        name="meeting_material_create",
    ),
    path(
        (
            "projects/<int:project_id>/cycles/<int:cycle_id>/board/"
            "meeting-materials/<int:meeting_material_id>/retry/"
        ),
        MeetingMaterialRetryView.as_view(),
        name="meeting_material_retry",
    ),
    path(
        (
            "projects/<int:project_id>/cycles/<int:cycle_id>/board/"
            "meeting-materials/<int:meeting_material_id>/drafts/"
            "<int:extraction_draft_id>/approve/"
        ),
        MeetingMaterialExtractionDraftApproveView.as_view(),
        name="meeting_material_extraction_draft_approve",
    ),
    path(
        (
            "projects/<int:project_id>/cycles/<int:cycle_id>/board/"
            "meeting-materials/<int:meeting_material_id>/drafts/"
            "<int:extraction_draft_id>/discard/"
        ),
        MeetingMaterialExtractionDraftDiscardView.as_view(),
        name="meeting_material_extraction_draft_discard",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/discussion/topics/<int:cluster_id>/",
        FeedbackClusterDiscussionUpdateView.as_view(),
        name="feedback_cluster_discussion_update",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/discussion/actions/add/",
        ActionItemCreateView.as_view(),
        name="action_item_create",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/discussion/actions/<int:action_item_id>/edit/",
        ActionItemUpdateView.as_view(),
        name="action_item_update",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/actions/<int:action_item_id>/complete/",
        ActionItemOwnerCompleteView.as_view(),
        name="action_item_owner_complete",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/discussion/decisions/add/",
        RetrospectiveDecisionCreateView.as_view(),
        name="retrospective_decision_create",
    ),
    path(
        "projects/<int:project_id>/cycles/<int:cycle_id>/board/discussion/decisions/<int:decision_id>/edit/",
        RetrospectiveDecisionUpdateView.as_view(),
        name="retrospective_decision_update",
    ),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
